
package com.exlibris.dps;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddRepresentationWebServices", targetNamespace = "http://dps.exlibris.com/", wsdlLocation = "http://depot.lias.be/dpsws/repository/AddRepresentationWebServices?wsdl")
public class AddRepresentationWebServices_Service
    extends Service
{

    private final static URL ADDREPRESENTATIONWEBSERVICES_WSDL_LOCATION;
    private final static WebServiceException ADDREPRESENTATIONWEBSERVICES_EXCEPTION;
    private final static QName ADDREPRESENTATIONWEBSERVICES_QNAME = new QName("http://dps.exlibris.com/", "AddRepresentationWebServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://depot.lias.be/dpsws/repository/AddRepresentationWebServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDREPRESENTATIONWEBSERVICES_WSDL_LOCATION = url;
        ADDREPRESENTATIONWEBSERVICES_EXCEPTION = e;
    }

    public AddRepresentationWebServices_Service() {
        super(__getWsdlLocation(), ADDREPRESENTATIONWEBSERVICES_QNAME);
    }


    public AddRepresentationWebServices_Service(URL wsdlLocation) {
        super(wsdlLocation, ADDREPRESENTATIONWEBSERVICES_QNAME);
    }


    public AddRepresentationWebServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }


    /**
     * 
     * @return
     *     returns AddRepresentationWebServices
     */
    @WebEndpoint(name = "AddRepresentationWebServicesPort")
    public AddRepresentationWebServices getAddRepresentationWebServicesPort() {
        return super.getPort(new QName("http://dps.exlibris.com/", "AddRepresentationWebServicesPort"), AddRepresentationWebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddRepresentationWebServices
     */
    @WebEndpoint(name = "AddRepresentationWebServicesPort")
    public AddRepresentationWebServices getAddRepresentationWebServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dps.exlibris.com/", "AddRepresentationWebServicesPort"), AddRepresentationWebServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDREPRESENTATIONWEBSERVICES_EXCEPTION!= null) {
            throw ADDREPRESENTATIONWEBSERVICES_EXCEPTION;
        }
        return ADDREPRESENTATIONWEBSERVICES_WSDL_LOCATION;
    }

}
