
package com.exlibris.dps;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataManagerServicesWS", targetNamespace = "http://dps.exlibris.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataManagerServicesWS {


    /**
     * 
     * @param pdsHandle
     * @return
     *     returns java.util.List<com.exlibris.dps.Process>
     * @throws UserAuthorizeException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMaintenanceProcessList", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetMaintenanceProcessList")
    @ResponseWrapper(localName = "getMaintenanceProcessListResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetMaintenanceProcessListResponse")
    public List<Process> getMaintenanceProcessList(
        @WebParam(name = "pdsHandle", targetNamespace = "")
        String pdsHandle)
        throws UserAuthorizeException_Exception
    ;

    /**
     * 
     * @param pdsHandle
     * @param setId
     * @return
     *     returns com.exlibris.dps.SetMembers
     * @throws UserAuthorizeException_Exception
     * @throws SetNotValidException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSetMembers", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetSetMembers")
    @ResponseWrapper(localName = "getSetMembersResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetSetMembersResponse")
    public SetMembers getSetMembers(
        @WebParam(name = "pdsHandle", targetNamespace = "")
        String pdsHandle,
        @WebParam(name = "setId", targetNamespace = "")
        long setId)
        throws SetNotValidException_Exception, UserAuthorizeException_Exception
    ;

    /**
     * 
     * @param pdsHandle
     * @param processId
     * @param pidList
     * @return
     *     returns java.lang.Long
     * @throws ProcessException_Exception
     * @throws UserAuthorizeException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "runProcessOnPids", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.RunProcessOnPids")
    @ResponseWrapper(localName = "runProcessOnPidsResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.RunProcessOnPidsResponse")
    public Long runProcessOnPids(
        @WebParam(name = "pdsHandle", targetNamespace = "")
        String pdsHandle,
        @WebParam(name = "processId", targetNamespace = "")
        long processId,
        @WebParam(name = "pidList", targetNamespace = "")
        List<String> pidList)
        throws ProcessException_Exception, UserAuthorizeException_Exception
    ;

    /**
     * 
     * @param pdsHandle
     * @param processExecutionId
     * @return
     *     returns java.lang.Integer
     * @throws ProcessException_Exception
     * @throws UserAuthorizeException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "abortProcess", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.AbortProcess")
    @ResponseWrapper(localName = "abortProcessResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.AbortProcessResponse")
    public Integer abortProcess(
        @WebParam(name = "pdsHandle", targetNamespace = "")
        String pdsHandle,
        @WebParam(name = "processExecutionId", targetNamespace = "")
        long processExecutionId)
        throws ProcessException_Exception, UserAuthorizeException_Exception
    ;

    /**
     * 
     * @param pdsHandle
     * @param path
     * @param pid
     * @return
     *     returns com.exlibris.dps.ExportEntityInfo
     * @throws ProcessException_Exception
     * @throws UserAuthorizeException_Exception
     * @throws InvalidIEException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exportIE", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.ExportIE")
    @ResponseWrapper(localName = "exportIEResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.ExportIEResponse")
    public ExportEntityInfo exportIE(
        @WebParam(name = "pdsHandle", targetNamespace = "")
        String pdsHandle,
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "path", targetNamespace = "")
        String path)
        throws InvalidIEException_Exception, ProcessException_Exception, UserAuthorizeException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns long
     * @throws ProcessException_Exception
     * @throws UserAuthorizeException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "runProcess", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.RunProcess")
    @ResponseWrapper(localName = "runProcessResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.RunProcessResponse")
    public long runProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1)
        throws ProcessException_Exception, UserAuthorizeException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.exlibris.dps.SetMembersInfo
     * @throws UserAuthorizeException_Exception
     * @throws SetNotValidException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateSetMembers", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UpdateSetMembers")
    @ResponseWrapper(localName = "updateSetMembersResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UpdateSetMembersResponse")
    public SetMembersInfo updateSetMembers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<String> arg2)
        throws SetNotValidException_Exception, UserAuthorizeException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHeartBit", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetHeartBit")
    @ResponseWrapper(localName = "getHeartBitResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetHeartBitResponse")
    public String getHeartBit();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.exlibris.dps.ProcessExecutionStatusInfo
     * @throws ProcessException_Exception
     * @throws UserAuthorizeException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessExecutionStatus", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetProcessExecutionStatus")
    @ResponseWrapper(localName = "getProcessExecutionStatusResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetProcessExecutionStatusResponse")
    public ProcessExecutionStatusInfo getProcessExecutionStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1)
        throws ProcessException_Exception, UserAuthorizeException_Exception
    ;

}
