
package com.exlibris.dps;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PermanentManagerWS", targetNamespace = "http://dps.exlibris.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PermanentManagerWS {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "storeMetadata", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.StoreMetadata")
    @ResponseWrapper(localName = "storeMetadataResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.StoreMetadataResponse")
    public void storeMetadata(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "storeSip", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.StoreSip")
    @ResponseWrapper(localName = "storeSipResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.StoreSipResponse")
    public String storeSip(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "storeDeletedIE", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.StoreDeletedIE")
    @ResponseWrapper(localName = "storeDeletedIEResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.StoreDeletedIEResponse")
    public String storeDeletedIE(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHeartBit", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetHeartBit")
    @ResponseWrapper(localName = "getHeartBitResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.GetHeartBitResponse")
    public String getHeartBit();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateMets", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UpdateMets")
    @ResponseWrapper(localName = "updateMetsResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.UpdateMetsResponse")
    public boolean updateMets(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteIE", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.DeleteIE")
    @ResponseWrapper(localName = "deleteIEResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.DeleteIEResponse")
    public String deleteIE(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "storeIE", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.StoreIE")
    @ResponseWrapper(localName = "storeIEResponse", targetNamespace = "http://dps.exlibris.com/", className = "com.exlibris.dps.StoreIEResponse")
    public String storeIE(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

}
