
package com.exlibris.dps;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PermanentManagerWS", targetNamespace = "http://dps.exlibris.com/", wsdlLocation = "http://depot.lias.be/dpsws/permanent/PermanentManagerWS?wsdl")
public class PermanentManagerWS_Service
    extends Service
{

    private final static URL PERMANENTMANAGERWS_WSDL_LOCATION;
    private final static WebServiceException PERMANENTMANAGERWS_EXCEPTION;
    private final static QName PERMANENTMANAGERWS_QNAME = new QName("http://dps.exlibris.com/", "PermanentManagerWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://depot.lias.be/dpsws/permanent/PermanentManagerWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERMANENTMANAGERWS_WSDL_LOCATION = url;
        PERMANENTMANAGERWS_EXCEPTION = e;
    }

    public PermanentManagerWS_Service() {
        super(__getWsdlLocation(), PERMANENTMANAGERWS_QNAME);
    }

    public PermanentManagerWS_Service(URL wsdlLocation) {
        super(wsdlLocation, PERMANENTMANAGERWS_QNAME);
    }

    public PermanentManagerWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PermanentManagerWS
     */
    @WebEndpoint(name = "PermanentManagerWSPort")
    public PermanentManagerWS getPermanentManagerWSPort() {
        return super.getPort(new QName("http://dps.exlibris.com/", "PermanentManagerWSPort"), PermanentManagerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PermanentManagerWS
     */
    @WebEndpoint(name = "PermanentManagerWSPort")
    public PermanentManagerWS getPermanentManagerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dps.exlibris.com/", "PermanentManagerWSPort"), PermanentManagerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERMANENTMANAGERWS_EXCEPTION!= null) {
            throw PERMANENTMANAGERWS_EXCEPTION;
        }
        return PERMANENTMANAGERWS_WSDL_LOCATION;
    }

}
